[package]
name = "apr"
version = "0.1.5"
edition = "2021"
authors = ["Jelmer Vernooĳ <jelmer@apache.org>"]
repository = "https://github.com/jelmer/apr-rs.git"
homepage = "https://github.com/jelmer/apr-rs"
license = "Apache-2.0"
description = "Rust bindings for Apache Portable Runtime"

[lib]
doctest = false

[dependencies]
ctor = "0.2.5"
url = { version = "2.4.1", optional = true }

[features]
url = ["dep:url"]

[build-dependencies]
bindgen = "0.68"
pkg-config = "0.3"
system-deps = "6.2"

[package.metadata.system-deps]
apr-1 = "*"
"apr-util-1" = "*"
